# site settings
title: Kevin Diem
subtitle:
email: contact@kevindiem.com
description: "Software Engineer and Web Developer making cool stuff in Hoboken, NJ."
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kevindiem.com # the base hostname & protocol for your site
author:
  name: Kevin Diem
  email: contact@kevindiem.com

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 5
form: meqwyvva

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/kgdiem
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/kevin-diem-9b817b104
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
